name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from Dependabot
        id: check
        run: |
          if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            echo "Is Dependabot PR"
            echo "approved=true" >> $GITHUB_ENV
          else
            echo "Not a Dependabot PR"
            echo "approved=false" >> $GITHUB_ENV
          fi

      - name: Approve PR
        if: env.approved == 'true'
        run: gh pr review --approve "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Auto-Merge
        if: env.approved == 'true'
        run: gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
