# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build, Test, and Push on Release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: "book-club-bot"
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      RELEASE_TAG: ${{ github.event.release.tag_name }}

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test || echo "No tests found"
    - run: |
        docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$RELEASE_TAG .
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image to DockerHub
      run: |
        docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME --all-tags
